const questions = [
  {
    id: 1,
    question: "Która planeta w Układzie Słonecznym jest największa?",
    answers: ["Wenus", "Mars", "Jowisz", "Saturn"],
    correct: 2,
  },
  {
    id: 2,
    question: "Ile kości ma dorosły człowiek?",
    answers: ["186", "206", "226", "256"],
    correct: 1,
  },
  {
    id: 3,
    question: "Kto napisał 'Pana Tadeusza'?",
    answers: [
      "Juliusz Słowacki",
      "Adam Mickiewicz",
      "Henryk Sienkiewicz",
      "Bolesław Prus",
    ],
    correct: 1,
  },
  {
    id: 4,
    question: "Jaki jest symbol chemiczny złota?",
    answers: ["Ag", "Au", "Fe", "Cu"],
    correct: 1,
  },
  {
    id: 5,
    question: "Ile wynosi pierwiastek kwadratowy z 144?",
    answers: ["10", "11", "12", "14"],
    correct: 2,
  },
  {
    id: 6,
    question: "Stolicą którego kraju jest Canberra?",
    answers: ["Nowej Zelandii", "Australii", "Kanady", "RPA"],
    correct: 1,
  },
  {
    id: 7,
    question: "W którym roku wybuchła II Wojna Światowa?",
    answers: ["1938", "1939", "1940", "1941"],
    correct: 1,
  },
  {
    id: 8,
    question: "Ile kolorów ma tęcza?",
    answers: ["5", "6", "7", "8"],
    correct: 2,
  },
  {
    id: 9,
    question: "Jak nazywa się największy ocean na Ziemi?",
    answers: ["Atlantycki", "Indyjski", "Arktyczny", "Spokojny"],
    correct: 3,
  },
  {
    id: 10,
    question: "Który pierwiastek ma symbol 'O'?",
    answers: ["Osm", "Ołów", "Tlen", "Ozon"],
    correct: 2,
  },
  {
    id: 11,
    question: "Ile sekund ma godzina?",
    answers: ["360", "600", "3600", "6000"],
    correct: 2,
  },
  {
    id: 12,
    question: "Kto namalował 'Mona Lisę'?",
    answers: [
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Pablo Picasso",
      "Michelangelo",
    ],
    correct: 1,
  },
  {
    id: 13,
    question: "Jak się nazywa stolica Polski?",
    answers: ["Kraków", "Gdańsk", "Warszawa", "Wrocław"],
    correct: 2,
  },
  {
    id: 14,
    question: "Ile to 7 × 8?",
    answers: ["48", "54", "56", "64"],
    correct: 2,
  },
  {
    id: 15,
    question: "Jaka jest temperatura wrzenia wody w stopniach Celsjusza?",
    answers: ["90°C", "95°C", "100°C", "110°C"],
    correct: 2,
  },
  {
    id: 16,
    question: "Kto jest autorem teorii względności?",
    answers: [
      "Isaac Newton",
      "Albert Einstein",
      "Niels Bohr",
      "Stephen Hawking",
    ],
    correct: 1,
  },
  {
    id: 17,
    question: "Ile kontynentów jest na Ziemi?",
    answers: ["5", "6", "7", "8"],
    correct: 2,
  },
  {
    id: 18,
    question: "Jakie jest największe zwierzę na świecie?",
    answers: ["Słoń afrykański", "Płetwal błękitny", "Rekin wielorybi", "Żyrafa"],
    correct: 1,
  },
  {
    id: 19,
    question: "W którym roku odbył się chrzest Polski?",
    answers: ["966", "1000", "1025", "1138"],
    correct: 0,
  },
  {
    id: 20,
    question: "Jak nazywa się najwyższa góra świata?",
    answers: ["K2", "Mount Everest", "Kilimandżaro", "Mont Blanc"],
    correct: 1,
  },
  // --- 100 nowych pytań ---
  {
    id: 21,
    question: "Jaki jest największy kontynent na Ziemi?",
    answers: ["Afryka", "Ameryka Północna", "Azja", "Europa"],
    correct: 2,
  },
  {
    id: 22,
    question: "Kto był pierwszym człowiekiem w kosmosie?",
    answers: ["Neil Armstrong", "Jurij Gagarin", "Buzz Aldrin", "John Glenn"],
    correct: 1,
  },
  {
    id: 23,
    question: "Ile dni ma rok przestępny?",
    answers: ["364", "365", "366", "367"],
    correct: 2,
  },
  {
    id: 24,
    question: "Które miasto nazywane jest 'Wiecznym Miastem'?",
    answers: ["Ateny", "Paryż", "Stambuł", "Rzym"],
    correct: 3,
  },
  {
    id: 25,
    question: "Jak nazywa się stolica Francji?",
    answers: ["Londyn", "Berlin", "Madryt", "Paryż"],
    correct: 3,
  },
  {
    id: 26,
    question: "Jaki jest symbol chemiczny srebra?",
    answers: ["Ag", "Si", "Sr", "Sv"],
    correct: 0,
  },
  {
    id: 27,
    question: "Ile wynosi liczba Pi w przybliżeniu do dwóch miejsc po przecinku?",
    answers: ["3,12", "3,14", "3,16", "3,18"],
    correct: 1,
  },
  {
    id: 28,
    question: "Kto napisał 'Dziady'?",
    answers: ["Juliusz Słowacki", "Cyprian Kamil Norwid", "Adam Mickiewicz", "Zygmunt Krasiński"],
    correct: 2,
  },
  {
    id: 29,
    question: "Ile to 12 do kwadratu?",
    answers: ["121", "144", "169", "196"],
    correct: 1,
  },
  {
    id: 30,
    question: "Jakie zwierzę widnieje w logo WWF?",
    answers: ["Słoń", "Tygrys", "Panda wielka", "Goryl"],
    correct: 2,
  },
  {
    id: 31,
    question: "Który gaz dominuje w atmosferze ziemskiej?",
    answers: ["Tlen", "Azot", "Dwutlenek węgla", "Wodór"],
    correct: 1,
  },
  {
    id: 32,
    question: "W jakim kraju leży Machu Picchu?",
    answers: ["Boliwia", "Meksyk", "Peru", "Kolumbia"],
    correct: 2,
  },
  {
    id: 33,
    question: "Który narząd odpowiada za filtrowanie krwi?",
    answers: ["Serce", "Nerki", "Płuca", "Żołądek"],
    correct: 1,
  },
  {
    id: 34,
    question: "Ile komór ma serce człowieka?",
    answers: ["2", "3", "4", "5"],
    correct: 2,
  },
  {
    id: 35,
    question: "Kto napisał 'Lalkę'?",
    answers: ["Stefan Żeromski", "Bolesław Prus", "Henryk Sienkiewicz", "Eliza Orzeszkowa"],
    correct: 1,
  },
  {
    id: 36,
    question: "W jakim języku mówi się w Egipcie?",
    answers: ["Arabskim", "Perskim", "Tureckim", "Hebrajskim"],
    correct: 0,
  },
  {
    id: 37,
    question: "Ile waży litr wody?",
    answers: ["0,5 kg", "1 kg", "1,5 kg", "2 kg"],
    correct: 1,
  },
  {
    id: 38,
    question: "Jak nazywa się największa pustynia na świecie?",
    answers: ["Sahara", "Gobi", "Antarktyda", "Atacama"],
    correct: 2,
  },
  {
    id: 39,
    question: "Kto jest autorem obrazu 'Gwiaździsta noc'?",
    answers: ["Claude Monet", "Vincent van Gogh", "Edvard Munch", "Salvador Dali"],
    correct: 1,
  },
  {
    id: 40,
    question: "W którym roku upadł Mur Berliński?",
    answers: ["1987", "1988", "1989", "1990"],
    correct: 2,
  },
  {
    id: 41,
    question: "Jakie jest najgłębsze jezioro na świecie?",
    answers: ["Morze Kaspijskie", "Bajkał", "Wielkie Jezioro Niewolnicze", "Tanganika"],
    correct: 1,
  },
  {
    id: 42,
    question: "Która z tych liczb jest liczbą pierwszą?",
    answers: ["21", "27", "31", "39"],
    correct: 2,
  },
  {
    id: 43,
    question: "Jak nazywa się najdłuższa rzeka w Polsce?",
    answers: ["Odra", "Warta", "Wisła", "Bug"],
    correct: 2,
  },
  {
    id: 44,
    question: "Co oznacza skrót DNA?",
    answers: ["Kwas dezoksyrybonukleinowy", "Kwas rybonukleinowy", "Dinukleotyd adeninowy", "Dezoksynukleozyd"],
    correct: 0,
  },
  {
    id: 45,
    question: "Który pierwiastek występuje w diamentach?",
    answers: ["Tlen", "Azot", "Wodór", "Węgiel"],
    correct: 3,
  },
  {
    id: 46,
    question: "Ile graczy jest jednocześnie na boisku w drużynie piłkarskiej?",
    answers: ["9", "10", "11", "12"],
    correct: 2,
  },
  {
    id: 47,
    question: "Jak nazywa się stolica Hiszpanii?",
    answers: ["Barcelona", "Madryt", "Walencja", "Sewilla"],
    correct: 1,
  },
  {
    id: 48,
    question: "Kto napisał 'Quo Vadis'?",
    answers: ["Bolesław Prus", "Stefan Żeromski", "Henryk Sienkiewicz", "Władysław Reymont"],
    correct: 2,
  },
  {
    id: 49,
    question: "Ile godzin to 360 minut?",
    answers: ["5", "6", "7", "8"],
    correct: 1,
  },
  {
    id: 50,
    question: "Który rok to początek XXI wieku?",
    answers: ["1999", "2000", "2001", "2002"],
    correct: 2,
  },
  {
    id: 51,
    question: "Jakie jest najmniejsze państwo na świecie?",
    answers: ["Monako", "San Marino", "Watykan", "Nauru"],
    correct: 2,
  },
  {
    id: 52,
    question: "Jaki jest wzór na pole koła?",
    answers: ["2πr", "πr²", "πr", "2πr²"],
    correct: 1,
  },
  {
    id: 53,
    question: "Który metal jest ciekły w temperaturze pokojowej?",
    answers: ["Żelazo", "Ołów", "Rtęć", "Cyna"],
    correct: 2,
  },
  {
    id: 54,
    question: "Ile kręgów ma człowiek w odcinku szyjnym kręgosłupa?",
    answers: ["5", "6", "7", "8"],
    correct: 2,
  },
  {
    id: 55,
    question: "Kto skomponował 'O Fortuna' z Carmina Burana?",
    answers: ["Johann Sebastian Bach", "Carl Orff", "Wolfgang Amadeus Mozart", "Richard Wagner"],
    correct: 1,
  },
  {
    id: 56,
    question: "Jak się nazywa stolica Włoch?",
    answers: ["Mediolan", "Neapol", "Rzym", "Turyn"],
    correct: 2,
  },
  {
    id: 57,
    question: "Ile boków ma trapez?",
    answers: ["3", "4", "5", "6"],
    correct: 1,
  },
  {
    id: 58,
    question: "W którym roku Polska wstąpiła do Unii Europejskiej?",
    answers: ["2002", "2003", "2004", "2005"],
    correct: 2,
  },
  {
    id: 59,
    question: "Jakie zwierzę jest symbolem Polski (godło)?",
    answers: ["Lew", "Żubr", "Orzeł biały", "Bocian"],
    correct: 2,
  },
  {
    id: 60,
    question: "Która planeta jest najbliższa Słońcu?",
    answers: ["Wenus", "Merkury", "Ziemia", "Mars"],
    correct: 1,
  },
  {
    id: 61,
    question: "Ile wynosi 2⁸? (2 do potęgi 8)",
    answers: ["64", "128", "256", "512"],
    correct: 2,
  },
  {
    id: 62,
    question: "Kto był twórcą Facebooka?",
    answers: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Elon Musk"],
    correct: 2,
  },
  {
    id: 63,
    question: "Jak nazywa się najwyższy szczyt w Polsce?",
    answers: ["Śnieżka", "Rysy", "Kasprowy Wierch", "Babia Góra"],
    correct: 1,
  },
  {
    id: 64,
    question: "Jakie jest BMI przy wadze 70 kg i wzroście 1,75 m?",
    answers: ["około 20", "około 23", "około 25", "około 28"],
    correct: 1,
  },
  {
    id: 65,
    question: "Który kolor powstaje z połączenia niebieskiego i żółtego?",
    answers: ["Fioletowy", "Zielony", "Pomarańczowy", "Brązowy"],
    correct: 1,
  },
  {
    id: 66,
    question: "Ile kwartałów ma rok?",
    answers: ["2", "3", "4", "6"],
    correct: 2,
  },
  {
    id: 67,
    question: "Kto jest autorem 'Chłopów'?",
    answers: ["Henryk Sienkiewicz", "Bolesław Prus", "Władysław Reymont", "Stefan Żeromski"],
    correct: 2,
  },
  {
    id: 68,
    question: "Jak nazywa się największa wyspa świata?",
    answers: ["Madagaskar", "Grenlandia", "Nowa Gwinea", "Borneo"],
    correct: 1,
  },
  {
    id: 69,
    question: "Jaki jest symbol chemiczny żelaza?",
    answers: ["Fe", "Ir", "Ze", "Zl"],
    correct: 0,
  },
  {
    id: 70,
    question: "W którym roku wynaleziono telefon?",
    answers: ["1876", "1886", "1896", "1906"],
    correct: 0,
  },
  {
    id: 71,
    question: "Jaka jest stolica Kanady?",
    answers: ["Toronto", "Ottawa", "Montreal", "Vancouver"],
    correct: 1,
  },
  {
    id: 72,
    question: "Ile to 15% z 200?",
    answers: ["20", "25", "30", "35"],
    correct: 2,
  },
  {
    id: 73,
    question: "Które zwierzę jest najszybsze na lądzie?",
    answers: ["Lew", "Gepard", "Struś", "Antylopa"],
    correct: 1,
  },
  {
    id: 74,
    question: "Jaki jest wzór chemiczny wody?",
    answers: ["CO₂", "NaCl", "H₂O", "CH₄"],
    correct: 2,
  },
  {
    id: 75,
    question: "Kto napisał 'Ferdydurke'?",
    answers: ["Bruno Schulz", "Witold Gombrowicz", "Czesław Miłosz", "Stanisław Lem"],
    correct: 1,
  },
  {
    id: 76,
    question: "Ile województw jest w Polsce?",
    answers: ["14", "15", "16", "17"],
    correct: 2,
  },
  {
    id: 77,
    question: "Jaka jest największa planeta w Układzie Słonecznym?",
    answers: ["Saturn", "Uran", "Neptun", "Jowisz"],
    correct: 3,
  },
  {
    id: 78,
    question: "Kto wynalazł żarówkę?",
    answers: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Benjamin Franklin"],
    correct: 1,
  },
  {
    id: 79,
    question: "W jakim kraju znajduje się Wieża Eiffla?",
    answers: ["Niemcy", "Włochy", "Francja", "Hiszpania"],
    correct: 2,
  },
  {
    id: 80,
    question: "Ile lat to dekada?",
    answers: ["5", "10", "20", "50"],
    correct: 1,
  },
  {
    id: 81,
    question: "Który z tych krajów NIE graniczy z Polską?",
    answers: ["Czechy", "Słowacja", "Węgry", "Ukraina"],
    correct: 2,
  },
  {
    id: 82,
    question: "Jaka jest stolica Niemiec?",
    answers: ["Monachium", "Frankfurt", "Hamburg", "Berlin"],
    correct: 3,
  },
  {
    id: 83,
    question: "Ile to 3³? (3 do potęgi 3)",
    answers: ["9", "18", "27", "36"],
    correct: 2,
  },
  {
    id: 84,
    question: "Kto napisał 'Małego Księcia'?",
    answers: ["Victor Hugo", "Antoine de Saint-Exupéry", "Jules Verne", "Albert Camus"],
    correct: 1,
  },
  {
    id: 85,
    question: "Jak nazywa się słynna krzywa wieża we Włoszech?",
    answers: ["Wieża w Bolonii", "Krzywa Wieża w Pizie", "Bazylika św. Marka", "Koloseum"],
    correct: 1,
  },
  {
    id: 86,
    question: "Ile par chromosomów ma człowiek?",
    answers: ["22", "23", "24", "46"],
    correct: 1,
  },
  {
    id: 87,
    question: "Jaki jest symbol chemiczny ołowiu?",
    answers: ["Ol", "Pb", "Ob", "Pl"],
    correct: 1,
  },
  {
    id: 88,
    question: "Kto był pierwszym królem Polski?",
    answers: ["Mieszko I", "Bolesław Chrobry", "Kazimierz Wielki", "Władysław Jagiełło"],
    correct: 1,
  },
  {
    id: 89,
    question: "W którym roku wybuchło Powstanie Warszawskie?",
    answers: ["1943", "1944", "1945", "1946"],
    correct: 1,
  },
  {
    id: 90,
    question: "Ile minut ma doba?",
    answers: ["1200", "1340", "1440", "1540"],
    correct: 2,
  },
  {
    id: 91,
    question: "Jaka jest waluta Wielkiej Brytanii?",
    answers: ["Euro", "Dolar", "Funt szterling", "Frank"],
    correct: 2,
  },
  {
    id: 92,
    question: "Który z tych języków jest językiem programowania?",
    answers: ["HTML", "CSS", "XML", "Python"],
    correct: 3,
  },
  {
    id: 93,
    question: "Jak nazywa się najdłuższa rzeka świata?",
    answers: ["Amazonka", "Nil", "Jangcy", "Missisipi"],
    correct: 1,
  },
  {
    id: 94,
    question: "Ile trwała I Wojna Światowa?",
    answers: ["2 lata", "3 lata", "4 lata", "5 lat"],
    correct: 2,
  },
  {
    id: 95,
    question: "Kto namalował 'Sąd Ostateczny' w Kaplicy Sykstyńskiej?",
    answers: ["Rafael", "Leonardo da Vinci", "Michelangelo", "Donatello"],
    correct: 2,
  },
  {
    id: 96,
    question: "Jaka jest stolica Czech?",
    answers: ["Bratysława", "Praga", "Wiedeń", "Budapeszt"],
    correct: 1,
  },
  {
    id: 97,
    question: "Ile księżyców ma Ziemia?",
    answers: ["0", "1", "2", "3"],
    correct: 1,
  },
  {
    id: 98,
    question: "Który gruczoł produkuje insulinę?",
    answers: ["Tarczyca", "Nadnercza", "Trzustka", "Przysadka"],
    correct: 2,
  },
  {
    id: 99,
    question: "Jak nazywa się największy ssak lądowy?",
    answers: ["Hipopotam", "Słoń afrykański", "Nosorożec biały", "Żyrafa"],
    correct: 1,
  },
  {
    id: 100,
    question: "W którym roku odkryto Amerykę przez Kolumba?",
    answers: ["1482", "1492", "1502", "1512"],
    correct: 1,
  },
  {
    id: 101,
    question: "Ile nut liczy oktawa?",
    answers: ["6", "7", "8", "12"],
    correct: 2,
  },
  {
    id: 102,
    question: "Jaki sport uprawia Robert Lewandowski?",
    answers: ["Tenis", "Koszykówkę", "Piłkę nożną", "Siatkówkę"],
    correct: 2,
  },
  {
    id: 103,
    question: "Kto napisał 'Mitologię' (zbiór mitów greckich dla polskiego czytelnika)?",
    answers: ["Zygmunt Kubiak", "Jan Parandowski", "Robert Graves", "Stanisław Stabryła"],
    correct: 1,
  },
  {
    id: 104,
    question: "Jaka jest stolica Rosji?",
    answers: ["Sankt Petersburg", "Moskwa", "Kijów", "Mińsk"],
    correct: 1,
  },
  {
    id: 105,
    question: "Ile żeber ma człowiek?",
    answers: ["10 par", "12 par", "14 par", "16 par"],
    correct: 1,
  },
  {
    id: 106,
    question: "Który z tych owoców ma najwięcej witaminy C?",
    answers: ["Jabłko", "Banan", "Cytryna", "Acerola"],
    correct: 3,
  },
  {
    id: 107,
    question: "Jaki kształt ma znak STOP?",
    answers: ["Kwadrat", "Trójkąt", "Ośmiokąt", "Koło"],
    correct: 2,
  },
  {
    id: 108,
    question: "W którym roku Karol Wojtyła został papieżem?",
    answers: ["1976", "1978", "1980", "1982"],
    correct: 1,
  },
  {
    id: 109,
    question: "Jaki jest symbol chemiczny magnezu?",
    answers: ["Ma", "Mn", "Mg", "Mh"],
    correct: 2,
  },
  {
    id: 110,
    question: "Kto jest autorem 'Solaris'?",
    answers: ["Jacek Dukaj", "Andrzej Sapkowski", "Stanisław Lem", "Olga Tokarczuk"],
    correct: 2,
  },
  {
    id: 111,
    question: "Ile waży mózg dorosłego człowieka (średnio)?",
    answers: ["około 0,5 kg", "około 1,0 kg", "około 1,4 kg", "około 2,0 kg"],
    correct: 2,
  },
  {
    id: 112,
    question: "Jak nazywa się największy polski port morski?",
    answers: ["Gdynia", "Szczecin", "Gdańsk", "Świnoujście"],
    correct: 2,
  },
  {
    id: 113,
    question: "Który rok jest rokiem założenia Rzymu (legendarne)?",
    answers: ["1000 p.n.e.", "753 p.n.e.", "509 p.n.e.", "44 p.n.e."],
    correct: 1,
  },
  {
    id: 114,
    question: "Jaki kolor otrzymamy mieszając czerwony z niebieskim?",
    answers: ["Zielony", "Pomarańczowy", "Fioletowy", "Brązowy"],
    correct: 2,
  },
  {
    id: 115,
    question: "Ile dni ma luty w roku nieprzestępnym?",
    answers: ["28", "29", "30", "31"],
    correct: 0,
  },
  {
    id: 116,
    question: "Kto skomponował 'Bolero'?",
    answers: ["Claude Debussy", "Maurice Ravel", "Frédéric Chopin", "Igor Strawinski"],
    correct: 1,
  },
  {
    id: 117,
    question: "Jakie państwo ma flagę z białym krzyżem na czerwonym tle?",
    answers: ["Dania", "Szwajcaria", "Szwecja", "Norwegia"],
    correct: 1,
  },
  {
    id: 118,
    question: "Ile wynosi suma kątów w trójkącie?",
    answers: ["90°", "180°", "270°", "360°"],
    correct: 1,
  },
  {
    id: 119,
    question: "Kto był żoną Zeusa w mitologii greckiej?",
    answers: ["Atena", "Afrodyta", "Hera", "Artemida"],
    correct: 2,
  },
  {
    id: 120,
    question: "Jaka jest stolica Turcji?",
    answers: ["Stambuł", "Ankara", "Izmir", "Antalya"],
    correct: 1,
  },
  {
    id: 121,
    question: "Ile w przybliżeniu wynosi liczba Avogadro?",
    answers: ["6,02 × 10²³", "3,14 × 10²³", "1,6 × 10¹⁹", "9,8 × 10²³"],
    correct: 0,
  },
  {
    id: 122,
    question: "Kto napisał 'Krytykę czystego rozumu'?",
    answers: ["Georg Hegel", "Immanuel Kant", "Friedrich Nietzsche", "Arthur Schopenhauer"],
    correct: 1,
  },
  {
    id: 123,
    question: "Jaki pierwiastek ma liczbę atomową 79?",
    answers: ["Platyna", "Srebro", "Złoto", "Rtęć"],
    correct: 2,
  },
  {
    id: 124,
    question: "Kto był ostatnim królem Polski?",
    answers: ["Stanisław August Poniatowski", "August III Sas", "Jan III Sobieski", "Zygmunt III Waza"],
    correct: 0,
  },
  {
    id: 125,
    question: "Gdzie powstał najstarszy uniwersytet na świecie?",
    answers: ["Paryż", "Oksford", "Bolonia", "Praga"],
    correct: 2,
  },
  {
    id: 126,
    question: "Kto napisał 'Fausta'?",
    answers: ["Friedrich Schiller", "Johann Wolfgang Goethe", "Heinrich Heine", "Thomas Mann"],
    correct: 1,
  },
  {
    id: 127,
    question: "Które państwo jako pierwsze przyznało kobietom prawo głosu?",
    answers: ["USA", "Nowa Zelandia", "Wielka Brytania", "Szwajcaria"],
    correct: 1,
  },
  {
    id: 128,
    question: "Co oznacza skrót HTML?",
    answers: ["HyperText Markup Language", "High Tech Modern Language", "Hyper Transfer Mode Language", "Home Tool Markup Language"],
    correct: 0,
  },
  {
    id: 129,
    question: "Kto skomponował 'Toccatę i fugę d-moll'?",
    answers: ["Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonio Vivaldi"],
    correct: 1,
  },
  {
    id: 130,
    question: "Jaka jest stolica Australii?",
    answers: ["Sydney", "Melbourne", "Perth", "Canberra"],
    correct: 3,
  },
];

const finalQuestions = [
  {
    id: "f1",
    question: "Jaka jest prędkość światła w próżni?",
    answers: [
      "ok. 300 000 km/s",
      "ok. 150 000 km/s",
      "ok. 1 000 000 km/s",
      "ok. 30 000 km/s",
    ],
    correct: 0,
  },
  {
    id: "f2",
    question: "Kto napisał 'Zbrodnię i karę'?",
    answers: [
      "Lew Tołstoj",
      "Fiodor Dostojewski",
      "Anton Czechow",
      "Iwan Turgieniew",
    ],
    correct: 1,
  },
  {
    id: "f3",
    question: "Ile nóg ma pająk?",
    answers: ["6", "8", "10", "12"],
    correct: 1,
  },
  {
    id: "f4",
    question: "Jakie jest chemiczne oznaczenie sodu?",
    answers: ["S", "So", "Na", "No"],
    correct: 2,
  },
  {
    id: "f5",
    question: "Który rok jest rokiem przestępnym?",
    answers: ["1900", "2000", "2100", "2022"],
    correct: 1,
  },
  {
    id: "f6",
    question: "Jaka jest waluta Japonii?",
    answers: ["Won", "Jen", "Juan", "Dong"],
    correct: 1,
  },
  {
    id: "f7",
    question: "Ile zer ma miliard?",
    answers: ["6", "7", "8", "9"],
    correct: 3,
  },
  {
    id: "f8",
    question: "Kto skomponował 'Cztery pory roku'?",
    answers: ["Bach", "Mozart", "Vivaldi", "Beethoven"],
    correct: 2,
  },
  {
    id: "f9",
    question: "Jaki jest główny składnik powietrza?",
    answers: ["Tlen", "Azot", "Dwutlenek węgla", "Argon"],
    correct: 1,
  },
  {
    id: "f10",
    question: "W jakim języku mówi się w Brazylii?",
    answers: ["Hiszpańskim", "Portugalskim", "Angielskim", "Francuskim"],
    correct: 1,
  },
];

// ===== POZIOMY TRUDNOŚCI =====
// 1 = łatwy, 2 = średni (domyślny), 3 = trudny.
// Pytania nieujęte w mapie są traktowane jako "średni".
const difficultyMap = {
  // łatwe
  1: 1, 2: 1, 5: 1, 8: 1, 10: 1, 11: 1, 13: 1, 14: 1, 15: 1, 17: 1,
  18: 1, 20: 1, 21: 1, 23: 1, 25: 1, 29: 1, 30: 1, 31: 1, 34: 1, 37: 1,
  46: 1, 47: 1, 49: 1, 56: 1, 57: 1, 59: 1, 60: 1, 65: 1, 66: 1, 69: 1,
  72: 1, 73: 1, 74: 1, 76: 1, 77: 1, 79: 1, 90: 1, 91: 1, 96: 1, 97: 1,
  99: 1, 102: 1, 104: 1, 107: 1, 114: 1, 115: 1, 118: 1, 120: 1,
  // trudne
  6: 3, 19: 3, 26: 3, 38: 3, 41: 3, 44: 3, 50: 3, 53: 3, 54: 3, 55: 3,
  64: 3, 70: 3, 71: 3, 75: 3, 93: 3, 95: 3, 98: 3, 101: 3, 103: 3, 105: 3,
  106: 3, 108: 3, 109: 3, 110: 3, 113: 3, 116: 3, 117: 3, 119: 3,
  121: 3, 122: 3, 123: 3, 124: 3, 125: 3, 126: 3, 127: 3, 128: 3, 129: 3, 130: 3,
  // finałowe (f1-f10)
  f1: 3, f2: 2, f3: 1, f4: 2, f5: 3, f6: 2, f7: 1, f8: 2, f9: 1, f10: 2,
};

questions.forEach((q) => {
  q.difficulty = difficultyMap[q.id] !== undefined ? difficultyMap[q.id] : 2;
});
finalQuestions.forEach((q) => {
  q.difficulty = difficultyMap[q.id] !== undefined ? difficultyMap[q.id] : 2;
});

// Filtruje pulę pytań po poziomie trudności ("latwy" | "sredni" | "trudny" | "mieszany").
function filterByDifficulty(pool, difficulty) {
  const levels = { latwy: 1, sredni: 2, trudny: 3 };
  const level = levels[difficulty];
  if (!level) return pool;
  return pool.filter((q) => q.difficulty === level);
}

module.exports = { questions, finalQuestions, filterByDifficulty };