// KWAKOUT — baza kart "Szaleństwo pytań". Szalone pytania na turę.
const szalonePytania = [
  { id: "s1", level: "lagodne", text: "Jaka jest Twoja najbardziej szalona historia z wakacji?" },
  { id: "s2", level: "lagodne", text: "Gdybyś mógł zamienić się życiem z celebrytą na jeden dzień — kto i co byś zrobił?" },
  { id: "s3", level: "lagodne", text: "Co jest najdziwniejszą rzeczą, którą kiedykolwiek zjadłeś?" },
  { id: "s4", level: "lagodne", text: "Jaki jest Twój najśmieszniejszy sposób na podryw?" },
  { id: "s5", level: "lagodne", text: "Gdybyś wygrał milion jutro rano — co kupujesz jako pierwsze?" },
  { id: "s6", level: "lagodne", text: "Jaka jest najbardziej absurdalna rzecz, w którą kiedyś uwierzyłeś?" },
  { id: "s7", level: "lagodne", text: "Co byś zrobił, gdybyś na 24h stał się niewidzialny?" },
  { id: "s8", level: "lagodne", text: "Jaki jest Twój najbardziej żenujący moment, który dziś Cię śmieszy?" },
  { id: "s9", level: "lagodne", text: "Który przedmiot z Twojego pokoju najlepiej Cię opisuje i dlaczego?" },
  { id: "s10", level: "lagodne", text: "Gdybyś mógł mieć jakąkolwiek supermoc — jaką i do czego byś jej użył?" },
  { id: "s11", level: "lagodne", text: "Jaka jest najdziwniejsza myśl, która przyszła Ci do głowy pod prysznicem?" },
  { id: "s12", level: "lagodne", text: "Kogo z obecnych zabrałbyś na bezludną wyspę i dlaczego?" },
  { id: "s13", level: "lagodne", text: "Jaka jest Twoja najbardziej kontrowersyjna opinia o jedzeniu?" },
  { id: "s14", level: "lagodne", text: "Co byś powiedział kosmitom, gdyby wylądowali teraz?" },
  { id: "s15", level: "lagodne", text: "Jaka jest najgłupsza rzecz, na którą wydałeś pieniądze?" },
  { id: "s16", level: "lagodne", text: "Gdybyś był duchem — kogo byś straszył i jak?" },
  { id: "s17", level: "lagodne", text: "Jaki jest Twój plan na zombie apokalipsę?" },
  { id: "s18", level: "lagodne", text: "Który film/serial najlepiej opisuje Twoje życie i dlaczego?" },
  { id: "s19", level: "lagodne", text: "Co jest najodważniejszą rzeczą, jaką zrobiłeś w tym roku?" },
  { id: "s20", level: "lagodne", text: "Gdybyś mógł cofnąć czas — co byś zmienił i dlaczego?" },
  { id: "s21", level: "lagodne", text: "Jaki jest najdziwniejszy komplement, jaki kiedykolwiek dostałeś?" },
  { id: "s22", level: "lagodne", text: "Co robisz, gdy myślisz, że nikt nie patrzy?" },
  { id: "s23", level: "lagodne", text: "Jaka jest Twoja tajna recepta na idealny wieczór?" },
  { id: "s24", level: "lagodne", text: "Kogo z obecnych najtrudniej rozgryźć i co byś o niego zapytał?" },
// Poziom "ostre" (18+) — pytania po bandzie.
  { id: "o1", level: "ostre", text: "Jaka jest Twoja najbardziej odważna rzecz, którą zrobiłeś po alkoholu?" },
  { id: "o2", level: "ostre", text: "Gdybyś mógł spędzić noc z dowolną osobą z obecnych — kogo byś wybrał i dlaczego?" },
  { id: "o3", level: "ostre", text: "Jaki jest najdziwniejszy sen erotyczny, jaki pamiętasz?" },
  { id: "o4", level: "ostre", text: "Jaka była Twoja najgorsza randka i dlaczego skończyła się katastrofą?" },
  { id: "o5", level: "ostre", text: "Jakie jest Twoje ulubione miejsce, w którym uprawiałeś seks (albo chciałbyś)?" },
  { id: "o6", level: "ostre", text: "Co jest najbardziej żenującą rzeczą, jaka przydarzyła Ci się w sypialni?" },
  { id: "o7", level: "ostre", text: "Kto z obecnych Twoim zdaniem miał najwięcej partnerów?" },
  { id: "o8", level: "ostre", text: "Jaka jest najdziwniejsza rzecz, która Cię podnieca?" },
  { id: "o9", level: "ostre", text: "Gdybyś na 24h stał się płcią przeciwną — co zrobiłbyś jako pierwsze?" },
  { id: "o10", level: "ostre", text: "Jaki jest Twój najbardziej niegrzeczny sekret, którego nie znają przyjaciele?" },
  { id: "o11", level: "ostre", text: "Jak daleko byłbyś w stanie się posunąć za milion złotych?" },
  { id: "o12", level: "ostre", text: "Jaka jest najgorsza rzecz, którą powiedziałeś podczas zbliżenia?" },
  { id: "o13", level: "ostre", text: "Co myślisz o trójkącie — zgodziłbyś się, gdyby nadarzyła się okazja?" },
  { id: "o14", level: "ostre", text: "Kto z obecnych jest Twoim zdaniem największym flirciarzem?" },
  { id: "o15", level: "ostre", text: "Jaka jest Twoja ulubiona gra wstępna po kilku drinkach?" },
  { id: "o16", level: "ostre", text: "Jaki był Twój najbardziej kompromitujący moment na imprezie?" },
  { id: "o17", level: "ostre", text: "Gdybyś mógł zamienić się partnerem z kimś z obecnych na jedną noc — z kim?" },
  { id: "o18", level: "ostre", text: "Co byś zrobił, gdybyś wiedział, że nikt nigdy się nie dowie?" },
  { id: "o19", level: "ostre", text: "Jaki jest Twój najśmielszy pomysł na randkę marzeń?" },
  { id: "o20", level: "ostre", text: "Kto z obecnych najprawdopodobniej pierwszy wyląduje w czyimś łóżku na tej imprezie?" }
];

module.exports = { szalonePytania };
