// KWAKOUT — baza kart "Prawda czy Wyzwanie"
// Poziomy: grzeczne | ostre | dla-par | alkoholowe

const truths = [
  // --- GRZECZNE ---
  { id: "t1", text: "Jaka jest Twoja najbardziej żenująca piosenka, którą znasz na pamięć?", level: "grzeczne" },
  { id: "t2", text: "Jaki jest Twój najdziwniejszy nawyk?", level: "grzeczne" },
  { id: "t3", text: "Kto z obecnych jest Twoim ulubieńcem i dlaczego?", level: "grzeczne" },
  { id: "t4", text: "Jakie było Twoje największe kłamstwo z dzieciństwa?", level: "grzeczne" },
  { id: "t5", text: "Co jest na Twojej liście „nigdy w życiu”?", level: "grzeczne" },
  { id: "t6", text: "Jaka jest najśmieszniejsza rzecz, która Ci się przydarzyła w szkole lub pracy?", level: "grzeczne" },
  { id: "t7", text: "Gdybyś mógł zamienić się życiem z kimś z tej grupy na jeden dzień, kto to byłby?", level: "grzeczne" },
  { id: "t8", text: "Jaka jest Twoja ukryta pasja, o której nikt nie wie?", level: "grzeczne" },
  { id: "t9", text: "Co byś zrobił, gdybyś był niewidzialny przez jeden dzień?", level: "grzeczne" },
  { id: "t10", text: "Jaki film lub serial oglądasz, gdy nikt nie patrzy?", level: "grzeczne" },
  { id: "t11", text: "Jaka jest Twoja ulubiona przekąska o 3 w nocy?", level: "grzeczne" },
  { id: "t12", text: "Co Cię najbardziej śmieszy w tej grupie?", level: "grzeczne" },
  { id: "t13", text: "Jaka była Twoja pierwsza praca i co w niej było najgorszego?", level: "grzeczne" },
  { id: "t14", text: "Którego z obecnych najdłużej znasz i jaka jest Wasza najlepsza historia?", level: "grzeczne" },
  { id: "t15", text: "Jaka jest najgłupsza rzecz, w którą kiedyś uwierzyłeś?", level: "grzeczne" },
  // --- OSTRE ---
  { id: "t16", text: "Jaka jest najbardziej krępująca rzecz, którą zrobiłeś z powodu sympatii?", level: "ostre" },
  { id: "t17", text: "Kogo z tej grupy pocałowałbyś pod warunkiem, że nikt się nie dowie?", level: "ostre" },
  { id: "t18", text: "Jaka była Twoja największa imprezowa wpadka?", level: "ostre" },
  { id: "t19", text: "Jakie jest najdziwniejsze miejsce, w którym Cię prawie przyłapano?", level: "ostre" },
  { id: "t20", text: "Co jest najodważniejszą rzeczą, jaką zrobiłeś dla kogoś, kto Ci się podobał?", level: "ostre" },
  { id: "t21", text: "Jaki jest Twój najbardziej skrywany sekret, który teraz wyjawisz?", level: "ostre" },
  { id: "t22", text: "Kto z obecnych najbardziej Ci się podoba i dlaczego?", level: "ostre" },
  { id: "t23", text: "Jaka była Twoja najgorsza randka w życiu?", level: "ostre" },
  { id: "t24", text: "Jakie jest Twoje najbardziej wstydliwe marzenie?", level: "ostre" },
  { id: "t25", text: "Jaki był Twój największy crush, o którym nigdy nikomu nie powiedziałeś?", level: "ostre" },
  { id: "t26", text: "Jaka jest najdziwniejsza rzecz, którą robisz, gdy jesteś sam?", level: "ostre" },
  { id: "t27", text: "Kogo z tej grupy najtrudniej jest Ci zrozumieć?", level: "ostre" },
  { id: "t28", text: "Jakie jest Twoje najbardziej zakazane pragnienie?", level: "ostre" },
  { id: "t29", text: "Jaki był Twój najbardziej niezręczny moment z rodzicami?", level: "ostre" },
  { id: "t30", text: "Co naprawdę myślisz o ex swojej/swojego przyjaciela?", level: "ostre" },
  // --- DLA PAR ---
  { id: "t31", text: "Co w Twoim partnerze najbardziej Cię rozczula?", level: "dla-par" },
  { id: "t32", text: "Jaka była Wasza najgorsza kłótnia i jak się skończyła?", level: "dla-par" },
  { id: "t33", text: "Co partner robi, czego nigdy byś mu nie powiedział, że Cię denerwuje?", level: "dla-par" },
  { id: "t34", text: "Jakie jest Twoje najbardziej romantyczne wspomnienie z partnerem?", level: "dla-par" },
  { id: "t35", text: "Co byś zmienił w Waszym związku, gdybyś mógł jedną rzecz?", level: "dla-par" },
  { id: "t36", text: "Kiedy ostatnio pomyślałeś o partnerze w najmniej oczekiwanej chwili?", level: "dla-par" },
  { id: "t37", text: "Jaka jest najdziwniejsza rzecz, którą robicie razem?", level: "dla-par" },
  { id: "t38", text: "Co najbardziej podoba Ci się w wyglądzie partnera?", level: "dla-par" },
  { id: "t39", text: "Jakie masz marzenie, które chciałbyś spełnić razem z partnerem?", level: "dla-par" },
  { id: "t40", text: "Co partner robi lepiej niż ktokolwiek inny?", level: "dla-par" },
  { id: "t41", text: "Jaka była Wasza pierwsza randka — opowiedz ją z detalami.", level: "dla-par" },
  { id: "t42", text: "Czego nauczyłeś się od partnera?", level: "dla-par" },
  { id: "t43", text: "Co byś chciał, żeby partner robił częściej?", level: "dla-par" },
  { id: "t44", text: "Jaka jest najzabawniejsza rzecz, która przytrafiła Wam razem?", level: "dla-par" },
  { id: "t45", text: "Jaki jest Wasz ulubiony wspólny rytuał?", level: "dla-par" },
  // --- ALKOHOLOWE ---
  { id: "t46", text: "Ile razy zdarzyło Ci się nie pamiętać końca imprezy?", level: "alkoholowe" },
  { id: "t47", text: "Jaka była Twoja najgorsza kacowa historia?", level: "alkoholowe" },
  { id: "t48", text: "Co najgorszego powiedziałeś komuś po alkoholu?", level: "alkoholowe" },
  { id: "t49", text: "Z kim z tej grupy najchętniej poszedłbyś na piwo i o czym byście rozmawiali?", level: "alkoholowe" },
  { id: "t50", text: "Jaki jest Twój najbardziej wstydliwy moment po pijaku?", level: "alkoholowe" },
  { id: "t51", text: "Czy kiedykolwiek udawałeś trzeźwego, choć nie byłeś?", level: "alkoholowe" },
  { id: "t52", text: "Jaka była Twoja najdroższa pijacka decyzja?", level: "alkoholowe" },
  { id: "t53", text: "Co robisz na imprezie, czego trzeźwy nigdy byś nie zrobił?", level: "alkoholowe" },
  { id: "t54", text: "Jaki jest Twój rekord w jedną noc (liczba drinków)?", level: "alkoholowe" },
  { id: "t55", text: "Czy kiedykolwiek napisałeś coś żenującego do kogoś po pijaku?", level: "alkoholowe" },
  { id: "t56", text: "Jaka jest najbardziej szalona rzecz, którą zrobiłeś po imprezie?", level: "alkoholowe" },
  { id: "t57", text: "Komu z tej grupy najchętniej byś postawił drinka?", level: "alkoholowe" },
  { id: "t58", text: "Jaki jest Twój ulubiony sposób na kaca?", level: "alkoholowe" },
  { id: "t59", text: "Czy kiedykolwiek tańczyłeś na stole?", level: "alkoholowe" },
  { id: "t60", text: "Jaka była Twoja najzabawniejsza pijacka wymówka?", level: "alkoholowe" },
];

const dares = [
  // --- GRZECZNE ---
  { id: "d1", text: "Zatańcz przez 30 sekund bez muzyki.", level: "grzeczne" },
  { id: "d2", text: "Naśladuj swojego ulubionego celebrytę przez minutę.", level: "grzeczne" },
  { id: "d3", text: "Mów z przesadnym akcentem przez kolejne 2 minuty.", level: "grzeczne" },
  { id: "d4", text: "Zrób 10 przysiadów i przy każdym powiedz komplement komuś z grupy.", level: "grzeczne" },
  { id: "d5", text: "Zadzwoń do mamy/taty i powiedz „kocham Cię” bez wyjaśniania.", level: "grzeczne" },
  { id: "d6", text: "Zaśpiewaj refren dowolnej piosenki jak w operze.", level: "grzeczne" },
  { id: "d7", text: "Stań na jednej nodze i opowiedz, co jadłeś na śniadanie.", level: "grzeczne" },
  { id: "d8", text: "Zrób najlepsze wrażenie innego gracza z tej grupy.", level: "grzeczne" },
  { id: "d9", text: "Powiedz alfabet od tyłu tak szybko, jak potrafisz.", level: "grzeczne" },
  { id: "d10", text: "Przez 2 minuty odpowiadaj na wszystko tylko „tak”.", level: "grzeczne" },
  { id: "d11", text: "Zrób 5 pajacyków, krzycząc „jestem mistrzem!”.", level: "grzeczne" },
  { id: "d12", text: "Udawaj kurczaka, dopóki nie przyjdzie Twoja kolej.", level: "grzeczne" },
  { id: "d13", text: "Opowiedz dowcip — jeśli nikt się nie zaśmieje, robisz 5 pompek.", level: "grzeczne" },
  { id: "d14", text: "Pokazuj przez minutę wybrany zawód bez słów (kalambury).", level: "grzeczne" },
  { id: "d15", text: "Zrób najdziwniejszą minę i utrzymaj ją 10 sekund, pozwalając zrobić zdjęcie.", level: "grzeczne" },
  // --- OSTRE ---
  { id: "d16", text: "Zadzwoń do ostatniej osoby w kontaktach i zaśpiewaj jej piosenkę.", level: "ostre" },
  { id: "d17", text: "Pokaż ostatnie zdjęcie w galerii telefonu i opowiedz jego historię.", level: "ostre" },
  { id: "d18", text: "Pozwól grupie opublikować wybrany przez nich (niewinny) status na Twoim koncie.", level: "ostre" },
  { id: "d19", text: "Naśladuj swój najbardziej żenujący ruch taneczny.", level: "ostre" },
  { id: "d20", text: "Powiedz komuś z grupy (w oczy) najlepszy komplement, jaki znasz.", level: "ostre" },
  { id: "d21", text: "Przez 3 minuty mów tylko szeptem, nawet gdy ktoś pyta normalnie.", level: "ostre" },
  { id: "d22", text: "Zrób 15 pompek, a przy każdej wyznaj jedną prawdę o sobie.", level: "ostre" },
  { id: "d23", text: "Pozwól komuś z grupy napisać i wysłać wiadomość z Twojego telefonu do wybranej osoby.", level: "ostre" },
  { id: "d24", text: "Udawaj zakochane małżeństwo z osobą po Twojej lewej przez 2 minuty.", level: "ostre" },
  { id: "d25", text: "Powiedz grupie, kto z obecnych ma największą szansę zostać Twoim crush-em.", level: "ostre" },
  { id: "d26", text: "Zatańcz „gorący” taniec do piosenki wybranej przez grupę.", level: "ostre" },
  { id: "d27", text: "Wyznaj coś, czego nigdy nie odważyłeś się powiedzieć na głos.", level: "ostre" },
  { id: "d28", text: "Zrób „romantyczne wyznanie” do przedmiotu w pokoju.", level: "ostre" },
  { id: "d29", text: "Przez minutę flirtuj z osobą, którą wskaże grupa.", level: "ostre" },
  { id: "d30", text: "Pokaż grupie swoje ostatnie 3 wyszukiwania w Google.", level: "ostre" },
  // --- DLA PAR ---
  { id: "d31", text: "Daj partnerowi 30-sekundowy masaż ramion.", level: "dla-par" },
  { id: "d32", text: "Przez 2 minuty mów partnerowi tylko komplementy.", level: "dla-par" },
  { id: "d33", text: "Wyznaj partnerowi 3 rzeczy, za które jesteś mu wdzięczny.", level: "dla-par" },
  { id: "d34", text: "Zatańcz z partnerem wolny taniec bez muzyki.", level: "dla-par" },
  { id: "d35", text: "Pocałuj partnera w czoło i powiedz mu, dlaczego go kochasz.", level: "dla-par" },
  { id: "d36", text: "Naśladuj partnera przez minutę (gesty, głos).", level: "dla-par" },
  { id: "d37", text: "Powiedz partnerowi jedną rzecz, której nigdy wcześniej mu nie powiedziałeś.", level: "dla-par" },
  { id: "d38", text: "Przytul partnera przez 30 sekund w ciszy.", level: "dla-par" },
  { id: "d39", text: "Zadzwoń do partnera i wyznaj mu miłość jak w telenoweli.", level: "dla-par" },
  { id: "d40", text: "Napisz partnerowi, za co go podziwiasz, i pokaż wiadomość grupie.", level: "dla-par" },
  { id: "d41", text: "Zróbcie razem najbardziej cringe'owe zdjęcie zakochanych.", level: "dla-par" },
  { id: "d42", text: "Przez minutę patrz partnerowi w oczy bez śmiechu.", level: "dla-par" },
  { id: "d43", text: "Opowiedz grupie Waszą najzabawniejszą wspólną historię.", level: "dla-par" },
  { id: "d44", text: "Zasymulujcie wspólnie scenę z ulubionego filmu.", level: "dla-par" },
  { id: "d45", text: "Daj partnerowi buziaka w policzek i powiedz najsłodsze słowo, jakie znasz.", level: "dla-par" },
  // --- ALKOHOLOWE ---
  { id: "d46", text: "Wypij łyk i wyznaj coś, czego nie powiedziałbyś na trzeźwo.", level: "alkoholowe" },
  { id: "d47", text: "Zrób „do dna” z osobą po Twojej prawej.", level: "alkoholowe" },
  { id: "d48", text: "Wypij łyk za każdą osobę, która powie, że Cię lubi.", level: "alkoholowe" },
  { id: "d49", text: "Zagraj w „nigdy przenigdy” — 3 pytania od grupy, każde „nigdy” = łyk.", level: "alkoholowe" },
  { id: "d50", text: "Wypij łyk i zaśpiewaj ulubioną piosenkę imprezową.", level: "alkoholowe" },
  { id: "d51", text: "Wypij łyk i powiedz najgorszy żart, jaki znasz.", level: "alkoholowe" },
  { id: "d52", text: "Zrób łyka i opowiedz swoją najbardziej wstydliwą historię imprezową.", level: "alkoholowe" },
  { id: "d53", text: "Wypij łyk i zrób 10 przysiadów.", level: "alkoholowe" },
  { id: "d54", text: "Zrób łyka i naśladuj pijaka (na wesoło) przez 30 sekund.", level: "alkoholowe" },
  { id: "d55", text: "Wypij łyk i wyznaj komuś z grupy coś miłego w oczy.", level: "alkoholowe" },
  { id: "d56", text: "Zagraj w „prawda czy łyk” — odmowa odpowiedzi = 2 łyki.", level: "alkoholowe" },
  { id: "d57", text: "Wypij łyk i zatańcz jak na weselu.", level: "alkoholowe" },
  { id: "d58", text: "Zrób łyka i zadzwoń do kogoś, mówiąc, że go kochasz.", level: "alkoholowe" },
  { id: "d59", text: "Wypij łyk i powiedz, kto z grupy ma najlepsze ruchy na parkiecie.", level: "alkoholowe" },
  { id: "d60", text: "Zrób łyka i opowiedz swój najgorszy dowcip.", level: "alkoholowe" },
];

function getPrompt(type, level) {
  const pool = (type === "truth" ? truths : dares).filter(
    (p) => p.level === level
  );
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { truths, dares, getPrompt };
